### ISSUE TITLE
有源码卖吗 多少钱？

### ISSUE THREAD

**Issue by xz592** [dev-xiaosa/VirtualAPPBusiness#2]
有源码卖吗 多少钱？

**Comment by dev-xiaosa** [comment]
> 有源码卖吗 多少钱？

有。8K

**Comment by dev-xiaosa** [comment]
@

> 有源码卖吗 多少钱？

嗯。

**Comment by dev-xiaosa** [comment]
> 有源码卖吗 多少钱？

你需要什么功能？最好帮你开发。

**Comment by xz592** [comment]
你好  vx联系方式多少？

**Comment by dev-xiaosa** [comment]
> 你好 vx联系方式多少？

xiaosa19960618

**Comment by Abdel-ilah** [comment]
> > 有源码卖吗 多少钱？



> 
> 
> > 有源码卖吗 多少钱？
> 
> 你需要什么功能？最好帮你开发。



> 
> 
> > 有源码卖吗 多少钱？
> 
> 你需要什么功能？最好帮你开发。

我怎么联系你？

**Comment by xz592** [comment]
你联系方式多少



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Abdel-ilah ***@***.***&gt;
发送时间: 2021年6月7日 09:45
收件人: dev-xiaosa/VirtualAPPBusiness ***@***.***&gt;
抄送: xz592 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[dev-xiaosa/VirtualAPPBusiness] 有源码卖吗 多少钱？ (#2)





   
有源码卖吗 多少钱？
     
有源码卖吗 多少钱？
  
你需要什么功能？最好帮你开发。
    
有源码卖吗 多少钱？
  
你需要什么功能？最好帮你开发。
  
我怎么联系你？
