### ISSUE TITLE
一个兴趣

### ISSUE THREAD

**Issue by Abdel-ilah** [dev-xiaosa/VirtualAPPBusiness#3]
我可以收到你的电子邮件吗？

**Comment by dev-xiaosa** [comment]
> 我可以收到你的电子邮件吗？

？？？？

**Comment by Abdel-ilah** [comment]
> > 我可以收到你的电子邮件吗？
> 
> ？？？？
 abdel-ilah@hotmail.fr
Send me your email

**Comment by Shahzaadeind** [comment]
I need source code please let me know nawaab.mumbai@gmail.com

**Comment by Shahzaadeind** [comment]
I'm looking source code of VA
If available please let me know
N-ind@outlook.com
